# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# Secrets are loaded from environment variables.
# Copy .env.example to .env and fill in appropriate values.
# ===================================================================

spring:
  datasource:
    username: ${POSTGRES_USER:WasteHelper}
    password: ${POSTGRES_PASSWORD:}

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ${JWT_BASE64_SECRET:}
